import type { ExtremeRRPlanStatus, NativeAccountPlanPolicy, NativeAccountPlanPreview } from "@trading-alert-dashboard/shared";

/**
 * How Trading Control reads a Native plan's per-account DEFAULT lookbacks.
 * Pure, display only.
 *
 * Each account shows its own configured default (UNSET when none) and what
 * that window would pick from the frozen plan. Nothing here selects, adopts or
 * executes anything: Native plans are planning only, and Native execution is
 * hard-disabled.
 */

export const NATIVE_PLANNING_ONLY_LABEL = "PLANNING ONLY";
export const NATIVE_EXECUTION_DISABLED_LABEL = "NATIVE EXECUTION DISABLED";
export const NATIVE_ACCOUNT_DEFAULT_UNSET = "UNSET";

/** A PENDING plan is still being generated by the background worker: never shown as READY. */
const PLAN_STATUS_LABEL: Readonly<Record<ExtremeRRPlanStatus, string>> = Object.freeze({
  PENDING: "PLANNING",
  READY: "READY",
  INVALID: "INVALID",
  ERROR: "ERROR",
});

export function nativePlanStatusLabel(status: ExtremeRRPlanStatus): string {
  return PLAN_STATUS_LABEL[status];
}

export function nativePlanStatusTone(status: ExtremeRRPlanStatus): "blue" | "green" | "yellow" | "red" {
  return status === "PENDING" ? "blue" : status === "READY" ? "green" : status === "INVALID" ? "yellow" : "red";
}

/** Display only: the exact decimal strings stay authoritative. */
function ratio(value: string | null): string {
  if (value === null) return "—";
  const n = Number(value);
  return Number.isFinite(n) ? `1:${Number(n.toFixed(2))}` : "—";
}

export interface NativeAccountDefaultRow {
  readonly label: string;
  /** "UNSET", "INVALID", or "<n> candles". */
  readonly value: string;
  /** Prices only when the account's window resolved to a valid candidate; otherwise the reason. */
  readonly detail: string | null;
  readonly tone: "green" | "gray" | "yellow" | "red";
}

/** The account's configured policy alone (shown even when there is no plan). */
export function presentNativeAccountPolicy(policy: NativeAccountPlanPolicy): NativeAccountDefaultRow {
  const label = `Account ${policy.account} Native default`;
  if (policy.state === "UNSET") return { label, value: NATIVE_ACCOUNT_DEFAULT_UNSET, detail: null, tone: "gray" };
  if (policy.state === "INVALID") return { label, value: "INVALID", detail: policy.reason, tone: "red" };
  return { label, value: `${policy.lookback} candles`, detail: null, tone: "green" };
}

/** One account's default applied to one frozen plan. */
export function presentNativeAccountDefault(preview: NativeAccountPlanPreview): NativeAccountDefaultRow {
  const label = `Account ${preview.account} Native default`;
  if (preview.state === "UNSET") return { label, value: NATIVE_ACCOUNT_DEFAULT_UNSET, detail: null, tone: "gray" };
  if (preview.state === "INVALID_POLICY") return { label, value: "INVALID", detail: preview.reason, tone: "red" };
  const value = `${preview.lookback} candles`;
  if (preview.state !== "RESOLVED") return { label, value, detail: preview.reason, tone: "yellow" };
  const partial = preview.complete === false && preview.actualCandles !== null ? ` (only ${preview.actualCandles} available)` : "";
  return { label, value: `${value}${partial}`, detail: `SL ${preview.stopLoss} · TP ${preview.takeProfit} · RR ${ratio(preview.riskRewardRatio)}`, tone: "green" };
}
