// Teddy native signal engine — Slice 1 (pure). See types.ts for the semantics.
// Explicit named exports, matching the package root's convention.

export type {
  CalendarAlignment,
  NativeConditionFlags,
  NativeEngineConfig,
  NativeEngineDiagnosticSnapshot,
  NativeEngineConfigInput,
  NativeEngineState,
  NativeFormingCandidate,
  NativeFormingCandidates,
  NativeHistoricalInput,
  NativeHistoricalPeriod,
  NativeHistoricalProjection,
  NativeHistoricalReport,
  NativeHistoricalResult,
  NativeHistoricalStateSemantics,
  NativeHistoricalTouch,
  NativeHtfAggregate,
  NativeHtfTrack,
  NativeCandidate,
  NativeCandidateBasis,
  NativeImmediateCandidate,
  NativeImmediateStepResult,
  NativeKline,
  NativeLevel,
  NativeLevelColor,
  NativeLevelCondition,
  NativeLevelDiagnostic,
  NativeLevelLifecycle,
  NativePartialPeriodPolicy,
  NativeRetestCandidate,
  NativeSignal,
  NativeSignalInputErrorCode,
  NativeSourceTf,
  NativeStepResult,
  NativeTimingMode,
  NativeTouchDirection,
} from "./types";
export {
  DEFAULT_CALENDAR_ALIGNMENT,
  NATIVE_DYNAMIC_HISTORICAL_STATE_SEMANTICS,
  NATIVE_HISTORICAL_STATE_SEMANTICS,
  NATIVE_LEVEL_LIFECYCLES,
  NATIVE_LIFECYCLE_PINE_V55_EDGE,
  NATIVE_LIFECYCLE_TEDDY_DYNAMIC_V1,
  NATIVE_LEVEL_CONDITIONS,
  NATIVE_SOURCE_TF_ORDER,
  NATIVE_TIMING_MODES,
  NativeSignalInputError,
  PINE_V55_INPUT_DEFAULTS,
  PINE_V5_FIRST_HISTORY_BAR_NO_EDGE,
  SWITCHOVER_TRUNCATED_CLOSED_BARS,
  createNativeEngineConfig,
  historicalStateSemanticsOf,
  nativeLevelLifecycleOf,
  pinePercentInputToFraction,
} from "./types";

export { advanceHtfAggregate, barFitsHtfPeriod, htfPeriodStartMs, projectPineHistoricalHtf } from "./htf-aggregate";
export {
  createNativeEngineState,
  evaluateLevelConditions,
  isDynamicLifecycle,
  reconstructImmediateCandidates,
  retestTimerGates,
  snapshotNativeEngineForNextBar,
  stepNativeEngine,
  stepNativeEngineWithImmediate,
} from "./engine";

export type { NativeImmediateReplayResult, NativeReplayResult } from "./replay";
export {
  reconstructCausalHistoricalState,
  reconstructHistoricalState,
  reconstructPineHistoricalState,
  replayNativeEngine,
  replayNativeEngineWithImmediate,
} from "./replay";
